_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
batch_size:
    value: 64
dropout:
    value: 0.5
epochs:
    value: 1
hidden_size:
    value: 64
input_size:
    value: 65536
learning_rate:
    value: 5e-06
model:
    value: model_type
