wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 64
input_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731881397.945848
    t:
      1:
      - 1
      - 15
      - 55
      2:
      - 1
      - 15
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 4
      - 5
